### PR TITLE
Deploy as beta version

### PR DESCRIPTION
**Pull request by stulees**
@tejohnso @santiagonoguez @jungeunyoon We will close and not merge PR #7  . `latest-version` will for the short-term require being updated manually.

### CODE REVIEW

**Comment by tejohnso** [comment]
@stulees Aren't we missing a copy of the beta manifests into the root GCS dir?

**Comment by stulees** [comment]
@tejohnso We're not automatically pushing anything into root. When we need to manually update root installers (stable) we will then need to also manually update the manifests.

**Comment by stulees** [comment]
@tejohnso Sorry, I misunderstood. You're right, the beta manifests need to be pushed to root. I'll make the change, thanks.

**Comment by stulees** [comment]
@tejohnso See last commit, thanks for catching. I'll update the other PRs also.

**Pull request merged**
